// import './jsx_study/jsx_study01'
// import './jsx_study/jsx_study02'
// import './jsx_study/jsx_study03'
// import './component-basic/first-component'
// import './component-basic/animal-container'
// import './component-basic/props-basic'
// import './component-basic/component_Q01'
// import './component-basic/props.children'
// import './component-basic/component_Q02'
// import './component-intermediate/state-study-1'
// import './component-intermediate/state-study-2'
// import './component-intermediate/component_Q01'
// import './component-intermediate/state-study-3'
import './component-intermediate/state-study-with-inner-object'