// import './jsx_study/jsx_study01'
// import './jsx_study/jsx_study02'
// import './jsx_study/jsx_study03'
// import './component-basic/first-component'
// import './component-basic/animal-container'
import './component-basic/props-basic'